# Python Cheat Sheet For ITDLWP
In this jupyter notebook, you'll learn the basic Python programming knowledge required for deep learning course,
[Intro To Deep Learning With Pytorch](https://github.com/erfanfathi/ITDLWP).<br>
(You can skip this tutorial if you're already familiar with Python and Numpy)

Topics :

0. [Hello World](#Hello-World)

1. [Variables and Data Types](#Variables-and-Data-Types)
    1. [Variable Assignment](#Variable-Assignment)
    2. [Calculations With Variables](#Calculations-With-Variables)
    3. [Types and Type Conversion](#Types-and-Type-Conversion)

2. [Strings](#Strings)
    1. [Strings Definition](#Strings-Definition)
    2. [String Operations](#String-Operations)
    3. [String Methods](#String-Methods)

3. [List](#List)
    1. [List Definition](#List-Definition)
    2. [Selecting List Elements](#Selecting-List-Elements)
    3. [List Operations](#List-Operations)
    4. [List Methods](#List-Methods)
    
4. [Dictionary](#Dictionary)
    1. [Dictionary Definition](#Dictionary-Definition)
    2. [Pythonic Way To Create A Dictionary](#Pythonic-Way-To-Create-A-Dictionary)
    3. [Looping Over Dictionary](#Looping-Over-Dictionary)

5. [Numpy](#Numpy)
    1. [Creating Arrays](#Creating-Arrays)
    2. [Array Initiallization](#Array-Initiallization)
    3. [Data Type In Numpy](#Data-Type-In-Numpy)
    4. [Inspecting An Arrays](#Inspecting-An-Arrays)
    5. [Mathematical Operations](#Mathematical-Operations)
    6. [Comparison](#Comparison)
    7. [Aggregate Functions](#Aggregate-Functions)
    8. [Copy Arrays](#Copy-Arrays)
    9. [Subsetting, Slicing, Indexing](#Subsetting,-Slicing,-Indexing)
    10. [Array Manipulations](#Array-Manipulations)
    
6. [Function Definition](#Function-Definition)

7. [Class Definition](#Class-Definition)

## Hello World

In [1]:
print('Hello World!')

Hello World!


## Variables and Data Types
Variables are nothing but reserved memory locations to store values. This means that when you create a variable you reserve some space in memory.

Based on the data type of a variable, the interpreter allocates memory and decides what can be stored in the reserved memory. Therefore, by assigning different data types to variables, you can store integers, decimals or characters in these variables.

The data stored in memory can be of many types.
Python has various standard data types that are used to define the operations possible on them and the storage method for each of them.

Python has five standard data types:
1. Numbers
2. String
3. List
4. Tuple
5. Dictionary

### Variable Assignment

In [2]:
x = 5

In [3]:
x

5

### Calculations With Variables

In [4]:
print(x + 2)        # Sum of two variables
print(x - 2)        # Subtraction of two variables
print(x * 2)        # Multiplication of two variables
print(x ** 2)       # Exponentiation of a variable
print(x % 2)        # Remainder of a variable
print(x / float(2)) # Division of a variable

7
3
10
25
1
2.5


### Types and Type Conversion

In [5]:
x = 3.14

In [6]:
x

3.14

In [7]:
print(str(x))   # Variables to strings
print(int(x))   # Variables to integers
print(float(x)) # Variables to floats
print(bool(x))  # Variables to booleans

3.14
3
3.14
True


## Strings
Strings in Python are identified as a contiguous set of characters represented in the quotation marks. Python allows for either pairs of single or double quotes.

### Strings Definition

In [8]:
my_string = 'Intro To Deep Learning With Pytorch'

In [9]:
my_string

'Intro To Deep Learning With Pytorch'

### String Operations

In [10]:
print(my_string * 2)        # Multiply
print(my_string + ' OMG ')  # Add
print('Intro' in my_string) # If intro in my_string return true

# Selecting String Elements
print(my_string[3])
print(my_string[9:22])

Intro To Deep Learning With PytorchIntro To Deep Learning With Pytorch
Intro To Deep Learning With Pytorch OMG 
True
r
Deep Learning


### String Methods

In [11]:
my_string

'Intro To Deep Learning With Pytorch'

In [12]:
print(my_string.upper())           # String to uppercase
print(my_string.lower())           # String to lowercase
print(my_string.count('W'))        # Count String elements
print(my_string.replace('e', 'i')) # Replace String elements
print(my_string.strip())           # Strip whitespaces

INTRO TO DEEP LEARNING WITH PYTORCH
intro to deep learning with pytorch
1
Intro To Diip Liarning With Pytorch
Intro To Deep Learning With Pytorch


## List
Lists are the most versatile of Python's compound data types. A list contains items separated by commas and enclosed within square brackets ([]).

note that all the items belonging to a list can be of different data type.

### List Definition

In [13]:
a = 'is'
b = 'nice'

my_list = ['my', 'list', a, b]
print(my_list)

my_list2 = [[4,5,6,7], [3,4,5,6]]
print(my_list2)

['my', 'list', 'is', 'nice']
[[4, 5, 6, 7], [3, 4, 5, 6]]


### Selecting List Elements

In [14]:
# Subset
print(my_list[1]) # Select item at index 1
print(my_list[-3]) # Select 3rd last item

# Slice
print(my_list[1:3]) # Select items at index 1 and 2
print(my_list[1:]) # Select items after index 0
print(my_list[:3]) # Select items before index 3
print(my_list[:]) # Copy my_list

# Subset Lists of Lists
print(my_list2[1][0]) # my_list[list][itemOfList]
print(my_list2[1][:2])

list
list
['list', 'is']
['list', 'is', 'nice']
['my', 'list', 'is']
['my', 'list', 'is', 'nice']
3
[3, 4]


### List Operations

In [15]:
print(my_list + my_list)
print(my_list * 2)
print(len(my_list2[0]) > 2)

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']
['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']
True


### List Methods

In [16]:
print(my_list.index(a)) # Get the index of an item

print(my_list.count(a)) # Count an item

my_list.append('!')     # Append an item at a time
print(my_list)

my_list.remove('!')     # Remove an item
print(my_list)

my_list.reverse()       # Reverse the list
print(my_list)

my_list.extend('!')     # Append an item
print(my_list)

print(my_list.pop(-1))  # Remove an item

my_list.insert(0,'!')   # Insert an item
print(my_list)

my_list.sort()          # Sort the list
print(my_list)

2
1
['my', 'list', 'is', 'nice', '!']
['my', 'list', 'is', 'nice']
['nice', 'is', 'list', 'my']
['nice', 'is', 'list', 'my', '!']
!
['!', 'nice', 'is', 'list', 'my']
['!', 'is', 'list', 'my', 'nice']


## Dictionary
Another useful data type built into Python is the dictionary. It is best to think of a dictionary as an unordered set of key: value pairs, with the requirement that the keys are unique (within one dictionary)

### Dictionary Definition

In [17]:
my_dict = {'jack': 4098, 'sape': 4139} # define a simple python dictionary
my_dict['guido'] = 4127                # add a element(key, value) to dictionary

In [18]:
my_dict

{'jack': 4098, 'sape': 4139, 'guido': 4127}

### Pythonic Way To Create A Dictionary

In [19]:
dic = {x: x**2 for x in [0,1,2,3,4,5]}

In [20]:
dic

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

### Looping Over Dictionary

In [21]:
for index, key in enumerate(my_dict):
    print(index, key)

for key, value in my_dict.items():
    print(key, value)

0 jack
1 sape
2 guido
jack 4098
sape 4139
guido 4127


## Numpy
numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [22]:
import numpy as np

### Creating Arrays

In [23]:
a = np.array([1,2,3]) # vector
a

array([1, 2, 3])

In [24]:
a.shape # getting shape of a vector

(3,)

In [25]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float) # 2D array
print(b)
print(b.shape)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
(2, 3)


In [26]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], 
                 dtype = float) # 3D Array
print(c)
print(c.shape)

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]
(2, 2, 3)


### Array Initiallization

In [27]:
zerosArr = np.zeros((3,4)) #Create an array of zeros
zerosArr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
onesArr = np.ones((2,3,4),dtype=np.int32) # Create an array of ones
onesArr

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [29]:
d = np.arange(10,25,5)  # Create an array of evenly spaced values args:start, end, step  
d

array([10, 15, 20])

In [30]:
arr = np.linspace(0,2,9)  # Create an array of evenly spaced values (number of samples)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
e = np.full((2,2),7)    # Create a constant array args:shape, data
e

array([[7, 7],
       [7, 7]])

In [32]:
f = np.eye(2)    # Create a 2X2 identity matrix
f

array([[1., 0.],
       [0., 1.]])

In [33]:
randomArr = np.random.random((2,2)) # Create an array with random values
randomArr

array([[0.09691554, 0.65176368],
       [0.98565469, 0.02895268]])

In [34]:
emptyArr = np.empty((3,2))  # Create an empty array
emptyArr

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

### Data Type In Numpy
1. np.int64: Signed 64-bit integer types
2. np.float32: Standard double-precision floating point
3. np.complex: Complex numbers represented by 128 floats
4. np.bool: Boolean type storing TRUE and FALSE values
5. np.object: Python object type
6. np.string_: Fixed-length string type
7. np.unicode_: Fixed-length unicode type

### Inspecting An Arrays
1. a.shape: Array dimensions
2. len(a): Length of array
3. b.ndim: Number of array dimensions
4. e.size: Number of array elements
5. b.dtype: Data type of array elements
6. b.dtype.name: Name of data type
7. b.astype(int): Convert an array to a different type

In [35]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [36]:
print(b.shape)
print(len(b))
print(b.ndim)
print(b.size)
print(b.dtype)
print(b.dtype.name)
print(b.astype(int))

(2, 3)
2
2
6
float64
float64
[[1 2 3]
 [4 5 6]]


### Mathematical Operations

In [37]:
g = a - b # Subtract   
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [38]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [39]:
b + a # Add

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [40]:
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [41]:
a / b # Divide

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [42]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [43]:
a * b # Multiply

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [44]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [45]:
np.exp(b) # Calculate the exponential of all elements in the input array.

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [46]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [47]:
np.sin(a) # Calculate the of all elements

array([0.84147098, 0.90929743, 0.14112001])

In [48]:
np.log(a) # Logarithm

array([0.        , 0.69314718, 1.09861229])

In [49]:
e.dot(f) # dot product of two arrays

array([[7., 7.],
       [7., 7.]])

### Comparison

In [50]:
a == b # Element-wise comparison

array([[False,  True,  True],
       [False, False, False]])

In [51]:
a < 2 # Element-wise comparison

array([ True, False, False])

In [52]:
np.array_equal(a, b) # Array-wise comparison

False

### Aggregate Functions

In [53]:
a

array([1, 2, 3])

In [54]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [55]:
a.sum() # Array-wise sum

6

In [56]:
a.min() # Array-wise minimum value

1

In [57]:
b.max(axis=0) # Maximum value of an array row

array([4., 5., 6.])

In [58]:
b.cumsum(axis=1) # Cumulative sum of the elements

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [59]:
a.mean() # Mean

2.0

In [60]:
np.median(b) # Median

3.5

In [61]:
np.corrcoef(a) # Correlation coefficient

1.0

In [62]:
np.std(b) # Standard deviation

1.5920810978785667

### Copy Arrays

In [63]:
h = a.view() # Create a view of the array with the same data
h

array([1, 2, 3])

In [64]:
np.copy(a) # Create a copy of the array

array([1, 2, 3])

In [65]:
h = a.copy() # Create a deep copy of the array
h

array([1, 2, 3])

### Subsetting, Slicing, Indexing

In [66]:
a

array([1, 2, 3])

In [67]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [68]:
# Subsetting
print(a[2])     # Select the element at the 2nd index
print(b[1,2])   # Select the element at row 0 column 2 ( equivalent to b[1][2] )
print(a[0:2])   # Select items at index 0 and 1
print(b[0:2,1]) # Select items at rows 0 and 1 in column 1
print(b[:1])    # Select all items at row 0 (equivalent to  b[0:1, :] )
print(c[1,...]) # Same as [1,:,:]
print(a[ : :-1])                  

# Boolean Indexing
print(a[a<2])   # Select elements from a less than 2

3
6.0
[1 2]
[2. 5.]
[[1.5 2.  3. ]]
[[3. 2. 1.]
 [4. 5. 6.]]
[3 2 1]
[1]


### Array Manipulations

In [69]:
a

array([1, 2, 3])

In [70]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [71]:
h

array([1, 2, 3])

In [72]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [73]:
# Transposing Array
i = np.transpose(b) # Permute array dimensions
print(i)
print(i.T)          # Permute array dimensions 

[[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [74]:
# Changing Array Shape
print(b)
print('Flatten', b.ravel())       # Flatten the array
print(g)
print('Reshape', g.reshape(3,-2)) # Reshape, but don’t change data 

[[1.5 2.  3. ]
 [4.  5.  6. ]]
Flatten [1.5 2.  3.  4.  5.  6. ]
[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
Reshape [[-0.5  0. ]
 [ 0.  -3. ]
 [-3.  -3. ]]


In [75]:
# Adding/Removing Elements
print(np.append(h,g))     # Append items to an array
print(np.insert(a, 1, 5)) # Insert items in an array
print(np.delete(a,[1]))   # Delete items from an array 

[ 1.   2.   3.  -0.5  0.   0.  -3.  -3.  -3. ]
[1 5 2 3]
[1 3]


In [76]:
# Combining Arrays
print(np.concatenate((a,d),axis=0)) # Concatenate arrays
print(np.vstack((a,b)))             # Stack arrays vertically (row-wise)
print(np.r_[e,f])                   # Stack arrays vertically (row-wise)
print(np.hstack((e,f)))             # Stack arrays horizontally (column-wise)
print(np.column_stack((a,d)))       # Create stacked column-wise arrays
print(np.c_[a,d])                   # Create stacked column-wise arrays 

[ 1  2  3 10 15 20]
[[1.  2.  3. ]
 [1.5 2.  3. ]
 [4.  5.  6. ]]
[[7. 7.]
 [7. 7.]
 [1. 0.]
 [0. 1.]]
[[7. 7. 1. 0.]
 [7. 7. 0. 1.]]
[[ 1 10]
 [ 2 15]
 [ 3 20]]
[[ 1 10]
 [ 2 15]
 [ 3 20]]


In [77]:
# Splitting Arrays
print(np.hsplit(a,3))  # Split the array horizontally at the 3rd index  
print(np.vsplit(c,2))  # Split the array vertically at the 2nd index

[array([1]), array([2]), array([3])]
[array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]]), array([[[3., 2., 1.],
        [4., 5., 6.]]])]


## Function Definition

In [78]:
def addFunc(a, b): # Function definition
    return a + b

In [79]:
print(addFunc(2,2)) # Call function

4


## Class Definition

In [80]:
class NewClass: # Class Definition
    def __init__(self, arg1, arg2): # Constructor
        self.arg1 = arg1
        self.arg2 = arg2
    def printValue(self):
        print(self.arg1)
        print(self.arg2)

In [81]:
instance = NewClass(2.2, 'hell') # Create a distance of NewClass

In [82]:
instance.printValue() # Call class function

2.2
hell
